select
    gll.ledger_id ledger_ledger_id ,
    gll.name ledger_name ,
    gll.short_name ledger_short_name ,
    gll.description ledger_description ,
    gll.ledger_category_code ledger_ledger_category_code ,
    gll.alc_ledger_type_code ledger_alc_ledger_type_code ,
    gll.object_type_code ledger_object_type_code ,
    gll.le_ledger_type_code ledger_le_ledger_type_code ,
    gll.completion_status_code ledger_completion_status_code ,
    gll.configuration_id ledger_configuration_id ,
    gll.chart_of_accounts_id ledger_chart_of_accounts_id ,
    gll.currency_code ledger_currency_code ,
    gll.period_set_name ledger_period_set_name ,
    gll.accounted_period_type ledger_accounted_period_type ,
    gll.first_ledger_period_name ledger_first_ledger_period_name ,
    gll.transaction_calendar_id ledger_transaction_calendar_id ,
    gll.daily_translation_rate_type ledger_daily_translation_rate_type ,
    gll.ledger_attributes ledger_ledger_attributes ,
    gll.implicit_ledger_set_id ledger_implicit_ledger_set_id ,
    gll.latest_opened_period_name ledger_latest_opened_period_name ,
    gll.latest_encumbrance_year ledger_latest_encumbrance_year ,
    gll.period_average_rate_type ledger_period_average_rate_type ,
    gll.period_end_rate_type ledger_period_end_rate_type ,
    gll.budget_period_avg_rate_type ledger_budget_period_avg_rate_type ,
    gll.budget_period_end_rate_type ledger_budget_period_end_rate_type ,
    gll.creation_date ledger_creation_date ,
    gll.created_by ledger_created_by
from
    ${source_hive_schema_name}.gl_ledgers gll
