select
    gjb.je_batch_id batch_je_batch_id ,
    gjb.set_of_books_id_11i batch_set_of_books_id_11i ,
    gjb.name batch_name ,
    gjb.status batch_status ,
    gjb.status_verified batch_status_verified ,
    gjb.budgetary_control_status batch_budgetary_control_status ,
    gjb.approval_status_code batch_approval_status_code ,
    gjb.default_period_name batch_default_period_name ,
    gjb.unique_date batch_unique_date ,
    gjb.earliest_postable_date batch_earliest_postable_date ,
    gjb.posted_date batch_posted_date ,
    gjb.date_created batch_date_created ,
    gjb.description batch_description ,
    gjb.control_total batch_control_total ,
    gjb.running_total_dr batch_running_total_dr ,
    gjb.running_total_cr batch_running_total_cr ,
    gjb.running_total_accounted_dr batch_running_total_accounted_dr ,
    gjb.running_total_accounted_cr batch_running_total_accounted_cr ,
    gjb.parent_je_batch_id batch_parent_je_batch_id ,
    gjb.request_id batch_request_id ,
    gjb.org_id batch_org_id ,
    gjb.chart_of_accounts_id batch_chart_of_accounts_id ,
    gjb.period_set_name batch_period_set_name ,
    gjb.accounted_period_type batch_accounted_period_type ,
    gjb.group_id batch_group_id ,
    gjb.approver_employee_id batch_approver_employee_id ,
    gjb.global_attribute_category batch_global_attribute_category 
from
    ${source_hive_schema_name}.gl_je_batches gjb
